version: "3"

services:

# ------> composer ------>
    composer_adboghi91jp9t4z26:
        container_name: composer_adboghi91jp9t4z26
        image: composer:latest
        volumes:
            - .././:/app
# <------ composer <------

# ------> mariadb ------>
    mariadb_adboghi91jp9t4z27:
        container_name: mariadb_adboghi91jp9t4z27
        image: mariadb:latest
        restart: 'on-failure'
        ports:
            - 3306:3306
        volumes:
            - .././skyflow/database/mariadb:/var/lib/mysql
        environment:
            MYSQL_DATABASE: coding
            MYSQL_USER: coding
            MYSQL_PASSWORD: coding
            MYSQL_ROOT_PASSWORD: coding
# <------ mariadb <------

# ------> symfony ------>
    symfony_adboghi91jp9t4z28:
        container_name: symfony_adboghi91jp9t4z28
        build: ./symfony
        image: skyflow/symfony
        restart: 'on-failure'
        ports:
            - 8089:80
        volumes:
            - ../:/coding
            - ./symfony/conf/apache2:/etc/apache2
            - ./symfony/conf/php7/php.ini:/etc/php7/php.ini
# <------ symfony <------